# Generated by Django 6.0.1 on 2026-01-11 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grimoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='書名')),
                ('description', models.TextField(verbose_name='解説')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
                ('stock', models.PositiveIntegerField(verbose_name='在庫数')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '受付中'), ('completed', '完了')], default='pending', max_length=20, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注文日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('price', models.PositiveIntegerField(verbose_name='購入時価格')),
                ('grimoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grimoires.grimoire')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grimoires.order')),
            ],
        ),
    ]
