# Generated by Django 6.0.1 on 2026-01-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grimoires', '0002_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='grimoire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grimoires/'),
        ),
    ]
